export { default as BookTickets } from "./BookTickets"
export { default as BooksSeats } from "./BooksSeats"
export { default as Details } from "./Details"
export { default as Home } from "./Home"
export { default as Page404 } from "./Page404"
export { default as Payments } from "./Payments"
export { default as Register } from "./Register"
export { default as Trailer } from "./Trailer"