export { default as AddMovie } from "./AddMovie"
export { default as AdminLogin } from "./AdminLogin"
export { default as BollyBook } from "./BollyBook"
export { default as Dashboard } from "./Dashboard"
export { default as AdminDetailsMovie } from "./AdminDetailsMovie"